#!/usr/bin/env bash

set -e

ZWACONF=./.zwaconf

TARGET=

get_version(){
      head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
}

sed_file() {

    while [ -n "$1" ]; do
        in=$1.in
        out=$1

        sed \
            -e "s/@VERSION@/${VERSION}/g" \
            $in > $out
        shift
    done
}

if [ -f $ZWACONF ]; then
  . $ZWACONF
fi

if [ -z "$TARGET" ]; then
  TARGET=$PWD/out
fi

if [ -z "$MAKE" ];then
  MAKE=make
fi

cmd=$1
shift

case "$cmd" in
  get-version)
    get_version
    ;;
  prepare-dist)
    VERSION=`get_version`
    ;;
  build-exclude-list|dist-exclude-list|prepare-dist)
    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ;;
  bootstrap)
    echo "No need to bootstrap"
    ;;
  configure)
    OPTIONS=`getopt -l "help,prefix:" 'p:' $@`
    if [ $? -ne 0 ]; then
      echo "$0: unknown flags..."
      exit 1
    fi

    eval set -- "$OPTIONS"
    while true ; do
      _arg=$1

      if [ -z "$_arg" ]; then
        break
      fi
      case $1 in
        -p|--prefix)
          shift
          TARGET="$1"
          ;;
        --prefix=*)
          TARGET=${1##*=}
          ;;
      esac
      shift
    done
    echo "TARGET=$TARGET" > $ZWACONF
    CONFOPTS=
    case "$ZBS_DIST" in
      solaris-*)
        if [ "$ZBS_ARCH" = "sparc64" ]; then
          solver=`echo $ZBS_DIST | cut -f2 -d'-'`
          CONFOPTS=" --build=sparc64-sun-solaris2.$solver"
          LDFLAGS="$LDFLAGS -Wl,-R/opt/syslog-ng/lib"
          if test -n "$LD_LIBRARY_PATH_64"; then
                  BUILD_LD_LIB_PATH=$LD_LIBRARY_PATH_64
                  LD_LIBRARY_PATH=$LD_LIBRARY_PATH_64
                  export LD_LIBRARY_PATH
          fi
        fi
        ;;
      tru64*)
          CFLAGS="$CFLAGS -D_XOPEN_SOURCE=500 -D_XOPEN_SOURCE_EXTENDED -D_OSF_SOURCE -D_POSIX_C_SOURCE -pthread"
        ;;
    esac

    if echo "$ZBS_DIST" | grep '^linux' >/dev/null 2>&1 && [ -n "$ZBS_ARCH" ] && [ "$ZBS_ARCH" = "i386" ];then
      CONFOPTS=--build=$ZBS_ARCH-unknown-`uname | tr '[A-Z]' '[a-z]'`-gnu
    fi
    export CFLAGS LDFLAGS

    ./configure --prefix $TARGET --disable-agent --disable-applications \
      --disable-manuals --disable-embedded-perl --with-default-snmp-version="3" \
      --with-openssl  --with-sys-contact="root" --with-sys-location="Unknown" \
      --with-logfile=none --with-persistent-directory=/opt/syslog-ng/var/snmp \
      --without-perl-modules --enable-reentrant --with-openssl=$TARGET $CONFOPTS
    $MAKE sedscript
    ;;
  make)
    case "$ZBS_DIST" in
      solaris-*)
        if [ "$ZBS_ARCH" = "sparc64" ]; then
          if test -n "$LD_LIBRARY_PATH_64"; then
                  LD_LIBRARY_PATH=$LD_LIBRARY_PATH_64
                  export LD_LIBRARY_PATH
          fi
        fi
        ;;
    esac
    case $1 in
      distclean)
        $MAKE distclean || true
        ;;
      install)
        # make install hates -jX ...
        unset MAKEFLAGS
        $MAKE $@
        ;;
      *) # unset CFLAGS LDFLAGS CC
        $MAKE $@
        ;;
    esac
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
