name: net-snmp
builder:
  name: BalabitBuilder
  configure_options: >
                --disable-agent --disable-applications
                --disable-manuals --disable-embedded-perl
                --with-default-snmp-version=3 --with-openssl
                --with-sys-contact=root --with-sys-location=Unknown
                --with-logfile=none
                --with-persistent-directory=/opt/syslog-ng/var/snmp
                --without-perl-modules --enable-reentrant
                --with-openssl=\${prefix}
  flags: "no-make-dist"
platforms:
  - linux-glibc2.11/amd64
  - aix-6.1/powerpc
